#!/usr/bin/env sh

echo "gzip ${NGINX_GZIP:-"on"};" > /etc/nginx/http.d/50-gzip.conf
echo "gzip_types ${NGINX_GZIP_TYPES:-"application/ecmascript application/javascript application/json application/xhtml+xml application/xml text/css text/ecmascript text/javascript text/plain text/xml"};" > /etc/nginx/http.d/50-gzip_types.conf
echo "gzip_proxied ${NGINX_GZIP_PROXIED:-"any"};" > /etc/nginx/http.d/50-gzip_proxied.conf
echo "absolute_redirect ${NGINX_ABSOLUTE_REDIRECT:-"on"};" > /etc/nginx/http.d/50-absolute_redirect.conf
echo "port_in_redirect ${PORT_IN_REDIRECT:-"on"};" > /etc/nginx/http.d/50-port_in_redirect.conf

echo "client_max_body_size ${PHP_POST_MAX_SIZE:-"8M"};" > /etc/nginx/server.d/50-client_max_body_size.conf
echo "root ${NGINX_ROOT:-"/app"};" > /etc/nginx/server.d/50-root.conf

echo "fastcgi_buffer_size ${NGINX_FASTCGI_BUFFER_SIZE:-"16k"};" > /etc/nginx/server.d/50-fastcgi_buffer_size.conf
echo "fastcgi_buffering ${NGINX_FASTCGI_BUFFERING:-"on"};" > /etc/nginx/server.d/50-fastcgi_buffering.conf
echo "fastcgi_buffers ${NGINX_FASTCGI_BUFFERS:-"16 16k"};" > /etc/nginx/server.d/50-fastcgi_buffers.conf
echo "fastcgi_busy_buffers_size ${NGINX_FASTCGI_BUSY_BUFFERS_SIZE:-"32k"};" > /etc/nginx/server.d/50-fastcgi_busy_buffers_size.conf

chown -R app:app /var/tmp/nginx /var/lib/nginx
