ARG PHP_VERSION="8.3"
FROM unit:php$PHP_VERSION

WORKDIR /app

# For running this image directly.
ARG PUID=1000
ARG PGID=1000
ENV PGID=$PGID PUID=$PUID
RUN addgroup --gid "$PGID" app
RUN adduser --uid "$PUID" \
            --ingroup app \
            --shell $(command -v bash) \
            --disabled-password \
            app

# For images building off of this.
ONBUILD ARG PUID=1000
ONBUILD ARG PGID=1000
ONBUILD ENV PGID=$PGID PUID=$PUID
ONBUILD RUN usermod -u "$PUID" app
ONBUILD RUN groupmod -g "$PGID" app

RUN cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini

COPY config/php-config.sh /docker-entrypoint.d/php-config.sh
COPY config/unit-config.json /docker-entrypoint.d/nginx-config.json

# Core configuration
ENV PHP__XDEBUG__CLIENT_HOST="host.docker.internal" \
    PHP__XDEBUG__MODE="develop,debug"
