#!/usr/bin/env sh

provided_max_children="${FPM_PM_MAX_CHILDREN:-"90%"}"

# Number of children should be determined by the amount of available memory.
if echo "$provided_max_children" | grep -qF '%'; then
  cgroup_limit="$(cat /sys/fs/cgroup/memory.max)"

  # No memory limit defined.
  if [ "$cgroup_limit" = "max" ]; then
    container_memory_limit_in_mb="$(grep "MemTotal:" /proc/meminfo | awk '{ print $2 / 1024 }')"
  else
    container_memory_limit_in_mb="$(echo "$cgroup_limit" | awk '{ print $0 / 1024 / 1024 }')"
  fi

  provided_php_memory_limit="${PHP_MEMORY_LIMIT:-"64M"}"

  # Determine PHP memory limit in MB
  if echo "$provided_php_memory_limit" | grep -qE '[Mm]$'; then
    php_memory_limit_in_mb="$provided_php_memory_limit"
  elif echo "$provided_php_memory_limit" | grep -qE '[Gg]$'; then
    php_memory_limit_in_mb="$((provided_php_memory_limit * 1024))"
  elif echo "$provided_php_memory_limit" | grep -qE '[Kk]$'; then
    php_memory_limit_in_mb="$((provided_php_memory_limit / 1024))"
  elif [ "$provided_php_memory_limit" = "-1" ]; then
    php_memory_limit_in_mb="$container_memory_limit_in_mb"
  else
    php_memory_limit_in_mb="$((provided_php_memory_limit / 1024 / 1024))"
  fi

  configured_max_children="$(
    awk \
      -v php_limit="$php_memory_limit_in_mb" \
      -v container_limit="$container_memory_limit_in_mb" \
      -v ratio="$provided_max_children" \
      'BEGIN { print int((container_limit * (int(ratio) / 100)) / php_limit) }'
  )"

  # Ensure there's at least one FPM process.
  if [ "$configured_max_children" -lt 1 ]; then
    configured_max_children=1
  fi
else
  configured_max_children="$provided_max_children"
fi

{
  echo "[www]"
  echo "user = app"
  echo "group = app"
  echo "access.log = /dev/null"
  echo "listen = /var/run/php-fpm.sock"
  echo "listen.owner = app"
  echo "listen.group = app"
  echo "pm = ${FPM_PM:-"static"}"
  echo "pm.max_children = ${configured_max_children}"
  echo "pm.min_spare_servers = ${FPM_PM_MIN_SPARE_SERVERS:-"1"}"
  echo "pm.max_spare_servers = ${FPM_PM_MAX_SPARE_SERVERS:-"3"}"
  echo "pm.max_requests = ${FPM_PM_MAX_REQUESTS:-"10000"}"
  echo "request_terminate_timeout = ${FPM_REQUEST_TERMINATE_TIMEOUT:-"0"}"
  echo "slowlog = ${FPM_SLOWLOG:-"/proc/self/fd/2"}"
  echo "request_slowlog_timeout = ${FPM_REQUEST_SLOWLOG_TIMEOUT:-"0"}"
  echo "clear_env = ${FPM_CLEAR_ENV:-"false"}"
} > /usr/local/etc/php-fpm.d/zz-pool-www.conf
