on:
  push:
    branches:
    - main

jobs:
  push:
    name: "${{ matrix.target }} @ ${{ matrix.php_version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version:
        - "8.0"
        - "8.1"
        - "8.2"
        variant:
        - fpm
        - cli
        alpine_version:
        - "3.18"
        include:
        - php_version: "8.0"
          alpine_version: "3.16"
        - variant: fpm
          target: www
        - variant: cli
          target: cli

    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Set up buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Load cache
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ matrix.php_version }}-${{ matrix.target }}-${{ github.sha }}
        restore-keys: ${{ matrix.php_version }}-${{ matrix.target }}-

    - name: Log in to Docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_LOGIN }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build
      uses: docker/build-push-action@v3
      with:
        target: "${{ matrix.target }}"
        build-args: |
          PHP_VERSION=${{ matrix.php_version }}-${{ matrix.variant }}
          ALPINE_VERSION=${{ matrix.alpine_version }}
        tags: ${{ vars.DOCKER_HUB_REPO }}/php:${{ matrix.php_version }}-${{ matrix.target }}
        platforms: linux/amd64,linux/arm64
        push: true
        cache-to: type=local,dest=/tmp/.buildx-cache-new
        cache-from: type=local,src=/tmp/.buildx-cache

    - name: Replace cache  # temp fix for https://github.com/docker/build-push-action/issues/252 & https://github.com/moby/buildkit/issues/1896.
      run: rm -rf /tmp/.buildx-cache && mv /tmp/.buildx-cache-new /tmp/.buildx-cache